### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by manojkmohan** [osmkerala/osmkerala-tasks#1]
My idea is to make a simple one using hugo. need to pick one from https://themes.gohugo.io/theme

**Comment by joicemjoseph** [comment]
Have we selected required theme ?

**Comment by manojkmohan** [comment]
Yes. but current one is okey for the starting purpose ? 

Any suggestions?

**Comment by joicemjoseph** [comment]
I dont have any suggestions. But I am sure it is inadequate. Navbar in mobile view is overflown
