### ISSUE TITLE
Water resources wiki pages

### ISSUE THREAD

**Issue by naveenpf** [osmkerala/osmkerala-tasks#12]
Kerala/Lagoons and Estuaries
Kerala/Lakes
Kerala/National Waterways
Kerala/Ponds
Kerala/Reservoirs
Kerala/Rivers
Kerala/Water Streams
Kerala/Waterways

**Comment by manojkmohan** [comment]
Is any National Waterways in Kerala. Conolly Canal ?

**Comment by manojkmohan** [comment]
- [ ] https://wiki.openstreetmap.org/wiki/Kerala#Water_Resources

**Comment by naveenpf** [comment]
These are the water-related items 

Water resources 
1. https://wiki.openstreetmap.org/wiki/Kerala/Rivers
2. https://wiki.openstreetmap.org/wiki/Kerala/Lakes
3. https://wiki.openstreetmap.org/wiki/Kerala/Reservoirs
4. https://wiki.openstreetmap.org/wiki/Kerala/Lagoons_and_Estuaries
5. https://wiki.openstreetmap.org/wiki/Kerala/Water_Streams
6. https://wiki.openstreetmap.org/wiki/Kerala/Ponds

Transport related
1. National waterways - https://wiki.openstreetmap.org/wiki/Kerala/National_Waterways
2. State waterways - https://wiki.openstreetmap.org/wiki/Kerala/Waterways

**Comment by naveenpf** [comment]
closing this .. structure is ready
