### ISSUE TITLE
qikpik mapathon prep

### ISSUE THREAD

**Issue by naveenpf** [osmkerala/osmkerala-tasks#14]
@arkarjun @jaisuvyas @naveenpf @planemad @Muzirian

**Comment by planemad** [comment]
Planning etherpad https://etherpad.wikimedia.org/p/qikpik-mapping-party

**Comment by naveenpf** [comment]
It is completed @planemad  @arkarjun 
Can we close this ?

**Comment by arkarjun** [comment]
> 
> 
> It is completed @planemad @arkarjun
> Can we close this ?

yes.

**Comment by naveenpf** [comment]
Event completed
