### ISSUE TITLE
Local brands to nsi.guide

### ISSUE THREAD

**Issue by naveenpf** [osmkerala/osmkerala-tasks#15]
Add local brands to nsi.guide

**Comment by naveenpf** [comment]
https://cryptpad.fr/sheet/#/3/sheet/edit/b6159994ad1dbcfb3bfcc63351241384/

**Comment by naveenpf** [comment]
Moving this to osm wiki
https://wiki.openstreetmap.org/wiki/India/Tags/NSI_Guide

**Comment by naveenpf** [comment]
Closing this.

**Comment by manojkmohan** [comment]
Is we need to write a blog post/ diary
