### ISSUE TITLE
Activate kerala.openstreetmap.in 

### ISSUE THREAD

**Issue by manojkmohan** [osmkerala/osmkerala-tasks#2]
Started the discussion here https://github.com/osm-in/openstreetmap.in/issues/35

**Comment by manojkmohan** [comment]
http://osmkerala.github.io is activated. Thanks @joicemjoseph.
After Closing this issue https://github.com/osm-in/openstreetmap.in/issues/35 we can close here too.

**Comment by naveenpf** [comment]
thanks @manojkmohan
