### ISSUE TITLE
Attribution of OSM Kerala in Mapathon Kerala

### ISSUE THREAD

**Issue by naveenpf** [osmkerala/osmkerala-tasks#20]
https://etherpad.wikimedia.org/p/Mapathon_kerala

**Comment by manojkmohan** [comment]
Updated the content and shared the draft to our Telegram/ WhatsApp for community review.

**Comment by manojkmohan** [comment]
Is we need a wikipage for future tracking and endorsement like things?

**Comment by naveenpf** [comment]
we can have subsection here

https://wiki.openstreetmap.org/wiki/Talk:Kerala_State_IT_Mission

**Comment by manojkmohan** [comment]
Is this content moved to wiki ?

**Comment by manojkmohan** [comment]
So we need to make this content in our website too.. with the context

**Comment by naveenpf** [comment]
yes .. it is in wiki

**Comment by naveenpf** [comment]
KSDI team didn't respond to the document created. Closing this issue. 
Website documentation 
osmkerala/osmkerala.github.io/issues/2
