### ISSUE TITLE
pick a suitable theme for our website

### ISSUE THREAD

**Issue by joicemjoseph** [osmkerala/osmkerala-tasks#21]
I got two theme suggestions. I felt both are not suitable. Either suggest a suitable theme or design one on our own.

**Comment by manojkmohan** [comment]
What about [this one ](https://themes.gohugo.io/hugo-travelify-theme/). banner slider images can replace by maps and stories. dont know it is mobile responsive. 
This also can check https://themes.gohugo.io/raditian-free-hugo-theme/

**Comment by manojkmohan** [comment]
It will be great to inspire from this https://github.com/osm-in/neighbourhood-mapping

**Comment by naveenpf** [comment]
website task.

**Comment by naveenpf** [comment]
Closing now. Released updated version of OSM website
