### ISSUE TITLE
Media repo of OSM activities in Kerala

### ISSUE THREAD

**Issue by naveenpf** [osmkerala/osmkerala-tasks#27]
https://github.com/osmkerala/osmkerala-tasks/tree/master/Media

@manojkmohan  @arkarjun @jaisuvyas

**Comment by manojkmohan** [comment]
Added some https://github.com/osmkerala/osmkerala-tasks/commit/9ba0f140ada12749edaa7109272535aab2c35f49

**Comment by naveenpf** [comment]
The structure is ready. Closing the task
