### ISSUE TITLE
create About us page

### ISSUE THREAD

**Issue by naveenpf** [osmkerala/osmkerala-tasks#4]

**Comment by naveenpf** [comment]
https://hackmd.io/@manojkmohan/BJa-7-cWP/edit

**Comment by naveenpf** [comment]
@joicemjoseph  can you please add this to website ?

**Comment by joicemjoseph** [comment]
yep!

**Comment by joicemjoseph** [comment]
![image](https://user-images.githubusercontent.com/672445/93721865-712fdf00-fbb0-11ea-92a5-d31bce9a045d.png)

Count it as a dummy content. I personally feel the content has to be polished.

**Comment by naveenpf** [comment]
Thanks @joicemjoseph . Yes we have to work on the content.

**Comment by manojkmohan** [comment]
Thanks @joicemjoseph

**Comment by manojkmohan** [comment]
We need a better theme

**Comment by naveenpf** [comment]
Closing this, tracked by website issues. osmkerala/osmkerala.github.io/issues/1
